[package]
name = "base-logging"
version = "0.3.0"
authors = ["Douglas Linder <douglas.linder@gmail.com>"]
edition = "2018"

[dependencies]
time = "0.1.39"
serde_derive = "*"
serde = "*"
serde_json = "*"